[package]
authors = ["Harrison Totty <harrisongtotty@gmail.com>"]
description = "Concatenate files and print them to stdout/stderr."
edition = "2018"
name = "cat"
publish = false
version = "0.1.0"

[dependencies.clap]
features = ["color"]
version = "2.32.0"