[package]
authors = ["Harrison Totty <harrisongtotty@gmail.com>"]
description = "Repeats the arguments provided to it on stdout/stderr."
edition = "2018"
name = "echo"
publish = false
version = "0.1.0"

[dependencies.clap]
features = ["color"]
version = "2.32.0"
